In [17]:
import apriltag
import cv2
import numpy as np
from vision_tools import *
# import vision_tools

In [18]:
tag_family  = 'tag36h11'
tag_size    = 0.20
tag_corners = tag_size / 2 * np.array([[-1,-1],[1,-1],[1,1],[-1,1]])


In [19]:
img = cv2.imread('data/skew.jpeg', cv2.IMREAD_GRAYSCALE) #, cv2.IMREAD_GRAYSCALE)


In [20]:

# cv2.imshow("default", img)
# cv2.waitKey(2000) # waits until a key is pressed
# cv2.destroyAllWindows() # destroys the window showing image

In [21]:
detector = apriltag.apriltag(tag_family)
K = np.array([[320, 0, 320],[0, 240, 320],[0, 0, 1]])

result = detector.detect(img)


detection = result[0]

print(detection['id'], '\t:  ', detection['center'])

detected_corners = detection['lb-rb-rt-lt']

hmg = cv2.findHomography(tag_corners, detected_corners)
print(hmg)
H = hmg[0]

print('H=',H)

R, T = poseFromHomography(H,K)
print('R=',R)
print('T=',T)


5 	:   [134.56400591  84.11374151]
(array([[ 493.48640433, -122.38162434,  134.56400591],
       [-104.090461  , -131.93636163,   84.11374151],
       [   0.68627873,    0.8197871 ,    1.        ]]), array([[1],
       [1],
       [1],
       [1]], dtype=uint8))
H= [[ 493.48640433 -122.38162434  134.56400591]
 [-104.090461   -131.93636163   84.11374151]
 [   0.68627873    0.8197871     1.        ]]
R= [[ 0.49228316 -0.77578265  0.39473861]
 [-0.69150689 -0.94490819  0.47153089]
 [ 0.00718626 -0.50509119 -1.00162144]]
T= [[-0.33331367]
 [-0.56532796]
 [ 0.57518701]]


In [22]:
# cv2.destroyAllWindows() # destroys the window showing image